nameOverride: ""
fullnameOverride: ""

environment: "prod"

image:
  repository: mateotorres2409/mateotorres2409
  tag: demo-nodejs-0.0.15
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: "0.1"
    memory: "320Mi"
  requests:
    cpu: "0.02"
    memory: "128Mi"

imagePullSecrets:
  - name: dockerhub-secret

appPort: 3000

env:
  static:
    NODE_ENV: "production"
  fromConfigMap: []
  fromSecret: []

scaledobject:
  enabled: true
  spec:
    minReplicaCount: 1
    maxReplicaCount: 5
    pollingInterval: 30
    cooldownPeriod:  150
    triggers:
    - type: prometheus
      metadata:
        serverAddress: https://prometheus-prod-56-prod-us-east-2.grafana.net/api/prom
        authModes: "basic"
        metricName: request_counter_total
        threshold: "10.0"
        query: |
          sum(rate(request_counter_total{action_type="uuid", k8s_namespace_name="demos", k8s_deployment_name="demo-nodejs"}[2m]))
      authenticationRef:
        name: grafana-prom-auth

replicaCount: 1

podAnnotations: {}
podLabels: {}

deploymentStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 0

revisionHistoryLimit: 3

service:
  type: ClusterIP
  port: 80
  protocol: TCP
  name: http
ingress:
  enabled: true
  annotations: 
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/enable-opentelemetry: "true"
    nginx.ingress.kubernetes.io/opentelemetry-operation-name: "demo-nodejs"
    cert-manager.io/cluster-issuer: k8s.mateo.local-ca
    cert-manager.io/common-name: demo-nodejs.k8s.mateo.local
    cert-manager.io/subject-organizations: "mateo.local"
    cert-manager.io/subject-organizationalunits: "MATEO TORRES ARREDONDO"
    cert-manager.io/subject-country: "CO"
    cert-manager.io/subject-province: "CUNDINAMARCA"
    cert-manager.io/subject-locality: "BOGOTA D.C."
  className: nginx
  host: demo-nodejs.k8s.mateo.local
  secretName: demo-nodejs.k8s.mateo.local-tls-ingress

gitCommit: 7eb040ac87e078add0d60b8f15b1b864a95b7775

podAnnotations:
  instrumentation.opentelemetry.io/inject-nodejs: "true"

configmap:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector-opentelemetry-collector:4317"
  PORT: 3000