nameOverride: ""
fullnameOverride: ""

environment: "prod"

image:
  repository: mateotorres2409/mateotorres2409
  tag: demo-python-0.0.16
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: "0.1"
    memory: "320Mi"
  requests:
    cpu: "0.02"
    memory: "128Mi"

configmap:
  NODE_API_URL: "http://demo-nodejs/uuid"

imagePullSecrets:
  - name: dockerhub-secret

appPort: 8000

env:
  static:
    NODE_ENV: "production"
  fromConfigMap: []
  fromSecret: []

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 75

scaledobject:
  enabled: true
  minReplicaCount: 1
  maxReplicaCount: 4
  cpuUtilizationPercentage: 80
  memoryUtilizationPercentage: 80

replicaCount: 2

podAnnotations: {}
podLabels: {}

deploymentStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 0

revisionHistoryLimit: 3

service:
  type: ClusterIP
  port: 80
  protocol: TCP
  name: http
ingress:
  enabled: true
  annotations: 
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/enable-opentelemetry: "true"
    nginx.ingress.kubernetes.io/opentelemetry-operation-name: "demo-python"
    cert-manager.io/cluster-issuer: k8s.mateo.local-ca
    cert-manager.io/common-name: demo-python.k8s.mateo.local
    cert-manager.io/subject-organizations: "mateo.local"
    cert-manager.io/subject-organizationalunits: "MATEO TORRES ARREDONDO"
    cert-manager.io/subject-country: "CO"
    cert-manager.io/subject-province: "CUNDINAMARCA"
    cert-manager.io/subject-locality: "BOGOTA D.C."
  className: nginx
  host: demo-python.k8s.mateo.local
  secretName: demo-python.k8s.mateo.local-tls-ingress

gitCommit: 03910f5094fe07c2801fd6f56dbe50732cc6db17

podAnnotations:
  instrumentation.opentelemetry.io/inject-python: "true"